### ISSUE TITLE
Expect exactly one securityGroup tagged with kubernetes.io/cluster/eks-1 for ENI

### ISSUE THREAD

**Issue by prikesh-patel** [kubernetes-sigs/aws-load-balancer-controller#1897]
This is a duplicate of #1181 and #1263.

I am getting the following error in the _aws-load-balancer-controller_ pod logs:

```
{"level":"error","ts":1616152638.9919386,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-game2048-service2-737679f196","namespace":"game-2048","error":"expect exactly one securityGroup tagged with kubernetes.io/cluster/eks-1 for eni eni-0036xxxxxxxxxxxxx, got: [sg-0255xxxxxxxxxxxxx sg-0dd9xxxxxxxxxxxxx]"}
```

My cluster has two security groups specified to the ENI, and both of these have the `kubernetes.io/cluster/eks-1` tag attached to them (from [terraform-aws-eks](https://github.com/terraform-aws-modules/terraform-aws-eks)).

Is there a way to get around this error?

**Comment by kishorj** [comment]
@prikesh-patel, in case there are multiple security groups, controller expects only one SG with the cluster tag. In your case, if you can ensure there is only one SG with the cluster tag, controller will recover from the reconciler error.

How did you end up with two SGs with the same cluster tag? Let us know if it is due to any confusion with the documentation.

**Comment by chriskinsman** [comment]
Hitting the same issue.  With AWS EKS 1.19 there is a security group created by EKS for the control plane master nodes that has the Kubernetes.io/cluster/{cluster-name} tag.  This is in addition to the security group that is created for the worker nodes by me with the same tag.  Wondering if this is a EKS 1.19 issue or something.

**Comment by chriskinsman** [comment]
Looks like also happens with EKS 1.18 and 1.17.  However terraform-aws-eks only creates one of these it looks like, the one for the workers.  The second is created by EKS itself it appears for the control plane.

**Comment by M00nF1sh** [comment]
@chriskinsman 
I'm not familiar with `terraform-aws-eks` tbh. but if that module already attaches the cluster SG(with the tag) to worker nodes and x-ENI. You shouldn't attach additional SG(with the tag) to worker nodes (you can attach additional SGs without the tag)

From EKS perspective, the SG for control plane and SG for worker node doesn't have relationships and don't need to be same. (i assume terraform-aws-eks used the same SG for both purpose from your description).

**Comment by chriskinsman** [comment]
It has two different security groups.  Played with some settings and got it working...

**Comment by prikesh-patel** [comment]
I've adjusted my ENI's to remove the cluster security group and include only the worker security group (both SG's created by terraform-aws-eks) as the cluster SG isn't needed. The problem has now been fixed and the errors in the *aws-load-balancer-controller* pod logs no longer appear.

**Comment by DzeryCZ** [comment]
I had similar problem. I'm using `eksctl` to provision the cluster.

The only thing I had to add to the configuration was `nodeGroups.securityGroups.withLocal: false` [Documentation](https://eksctl.io/usage/schema/#nodeGroups-securityGroups-withLocal)

**Comment by Charles-Johnson** [comment]
For those using `terraform-aws-eks` it looks like you can disable the cluster security group via the [`attach_cluster_primary_security_group` setting](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/18.16.0#security-groups)

**Comment by GouseAligne** [comment]
Using terraform-aws-eks and this issue has just started to show up. Any help will be appreciated.

**Comment by rjshk013** [comment]
In my case I have accidentally added the tag (kubernetes.io/cluster/my-cluster) to the cluster security group(description of sg : EKS created security group applied to ENI that is attached to EKS Control Plane master nodes, as well as any managed workloads.) When I removed it from the sg ,errors gone& aws load balancer controller gave expected output from the browser.I was spin up cluster by eksctl

**Comment by grzleadams** [comment]
For anyone still interested, I did find that this is documented in the [module FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#i-received-an-error-expect-exactly-one-securitygroup-tagged-with-kubernetesioclustername-).

**Comment by hahasheminejad** [comment]
For those having issues with the ALB controller complaining about finding zero SG though one SG is already tagged with `kubernetes.io/cluster/<cluster-name>: owned`

`expect exactly one securityGroup tagged with kubernetes.io/cluster/<cluster-name> for eni eni-XXXXX, got: []"}`

To fix this, go to AWS EC2 console and find the ENI mentioned in the error message above (eni-XXXXX), then attach the  `kubernetes.io/cluster/<cluster-name>: owned` to one of the Security Groups attached to that ENI.

**Comment by kasvith** [comment]
I had the same issue

the thing is i created the Cluster using `eksctl`, as instructed by @hahasheminejad i added a tag to a SG and it worked

But shouldn't controller do it automatically?

**Comment by NigelRook** [comment]
The way I fixed this. in my setup (terraform-aws-modules/eks/aws terraform module + karpenter) was to set `create_cluster_primary_security_group_tags = false` in that terraform module. This preventes the karpenter discovery tag being added to the defauly security group, which means only the security groups actually created and managed by the terraform module got attached to karpenter nodes

**Comment by bareksml** [comment]
Hey, in my particular case `create_cluster_primary_security_group_tags = false` was useless. It only removed some general tags while `kubernetes.io/cluster/clustername: owned` was still present. I am experimenting with `create_node_security_group = false` and my initial results are good however no idea if there will be any side effects related to this reconfiguration.

**Comment by voidlily** [comment]
I ran into a similar issue with EKS auto mode and the terraformed node security group from terraform-aws-modules. I was using the following securityGroupSelectorTerms

```
  securityGroupSelectorTerms:
    - tags:
        kubernetes.io/cluster/name: "owned"
```

This was picking up both my terraformed node security group, and the one auto mode created automatically. I fixed this by adding another tag to the terraformed security group

```
  node_security_group_tags = {
    "sg-type" = "node"
  }
```

And adding that tag to the securityGroupSelector

```
  securityGroupSelectorTerms:
    - tags:
        kubernetes.io/cluster/name: "owned"
        sg-type: "node"
```

**Comment by 1oglop1** [comment]
> I ran into a similar issue with EKS auto mode and the terraformed node security group from terraform-aws-modules. I was using the following securityGroupSelectorTerms
> 
> ```
>   securityGroupSelectorTerms:
>     - tags:
>         kubernetes.io/cluster/name: "owned"
> ```
> 
> This was picking up both my terraformed node security group, and the one auto mode created automatically. I fixed this by adding another tag to the terraformed security group
> 
> ```
>   node_security_group_tags = {
>     "sg-type" = "node"
>   }
> ```
> 
> And adding that tag to the securityGroupSelector
> 
> ```
>   securityGroupSelectorTerms:
>     - tags:
>         kubernetes.io/cluster/name: "owned"
>         sg-type: "node"
> ```

@voidlily Could you please share where exactly you applied `securityGroupSelectorTerms`? I inherited an eks k8s cluster with many things, and I am not yet thoroughly familiar with all the niches.

**Comment by Luke-Humphreys** [comment]
I ran into this issue when provisioning a new cluster using the aws-load-balancer-controller and karpenter.
This issue arises when a node has two SGs attached to it that contain the tag `kubernetes.io/cluster/foobar: owned`

First check the SGs that are attached to your EKS nodes to check to see if it has two or more SGs attached with the owned tag.

If it does it means your karpenter `EC2NodeClass` `securityGroupSelectorTerms` are too broad and so to fix it, update the `securityGroupSelectorTerms` to select only a single SG.

An example:

```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 20.35.0"
  
  .............................
  .............................
  node_security_group_tags       = { Name = format("%s-node-security-group", local.cluster_name) }
  tags = {
    "karpenter.sh/discovery" = local.cluster_name
  }
}
```

This adds the karpenter discovery tag to all SGs created by the EKS module, including the cluster-sg that eks creates when provisioned.

In my old karpenter EC2NodeClass I had this config which was the root cause of the issue:
```
    apiVersion: karpenter.k8s.aws/v1
    kind: EC2NodeClass
    metadata:
      name: default
    spec:
      ........
      ........
      securityGroupSelectorTerms:
        - tags:
            karpenter.sh/discovery: "${local.cluster_name}"
```

This meant that karpenter attaches all SGs with the `karpenter.sh/discovery` tag, **including** the cluster-sg that also has the 
 `kubernetes.io/cluster/foobar: owned` tag. This is what was causing problems.

I updated the EC2NodeClass to be:

```
    apiVersion: karpenter.k8s.aws/v1
    kind: EC2NodeClass
    metadata:
      name: default
    spec:
      ........
      ........
      securityGroupSelectorTerms:
        - tags:
            karpenter.sh/discovery: "${local.cluster_name}"
            Name: "${local.cluster_name}-node-security-group"
```

This ensured that the karpenter nodes only get the node_security_group attached that is created by the eks module.

This fixed the issue for me.

Hopefully this helps someone else having the same problem.
