### ISSUE TITLE
routing to multiple hosts with different SSL certs ARN with NLB

### ISSUE THREAD

**Issue by wwteo** [kubernetes-sigs/aws-load-balancer-controller#2684]
**Describe the bug**
The `service.beta.kubernetes.io/aws-load-balancer-ssl-cert` annotation can only assign one SSL certificate from ACM. According to documentation, it should be able to assign multiple SSL certificates as it takes in a StringList https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/guide/service/annotations.md
The controller issues a warning event that assumes a string instead of a stringlist.
`Error syncing load balancer: failed to ensure load balancer: error updating load balancer listener: "ValidationError: Certificate ARN 'arn:aws:acm:<region>:<account_id>:certificate/<uuid>,arn:aws:acm:<region>:<account_id>:certificate/<uuid>' is not valid\n\tstatus code: 400, request id: 2091d6fd-c98c-4a3d-a1ec-db38aab498df"`

**Steps to reproduce**
Place a stringlist into service.beta.kubernetes.io/aws-load-balancer-ssl-cert
**Expected outcome**
The NLB should have multiple SSL certificates on its listeners

**Environment**

* AWS Load Balancer controller version 2.4.2
* Kubernetes version
* Using EKS (yes/no), if so version? yes 1.21

**Additional Context**:

PS: When manually assigning multiple SSL certificates in the NLB with the AWS console, the ingress works via hosts routing.

**Comment by empeekdev** [comment]
We have exactly the same issue that happened to us few minutes ago

**Comment by empeekdev** [comment]
@wwteo was you able to solve this issue?

**Comment by wwteo** [comment]
> @wwteo was you able to solve this issue?

no

**Comment by iusergii** [comment]
EKS - v1.22.9-eks-a64ea69, Controller - 2.4.2 works for me:
```yaml
service.beta.kubernetes.io/aws-load-balancer-ssl-cert: >-
          arn:aws:acm:us-east-1:xxxxxxx:certificate/884f730d-4f4e-490d-bca9-31604f218240,
          arn:aws:acm:us-east-1:xxxxxxx:certificate/ea98d10e-c7e8-4ed9-bc29-8ba12a22c437,
          arn:aws:acm:us-east-1:xxxxxxx:certificate/8a5614c8-4e27-435d-b624-ff8437b3ba9b,
          arn:aws:acm:us-east-1:xxxxxxx:certificate/34261a24-5594-4319-a62f-73a6ef8a6c43,
          arn:aws:acm:us-east-1:xxxxxxx:certificate/a27aaffc-ea6d-466f-bfb8-697c1a869fe4,
          arn:aws:acm:us-east-1:xxxxxxx:certificate/156da266-d4ab-47ab-9a2b-d5358a22df3b,
          arn:aws:acm:us-east-1:xxxxxxx:certificate/23e04e3a-9ffd-4613-bb8c-41b7336812bb
```

**Comment by jozenstar** [comment]
@empeekdev @wwteo Have you guys tried the solution suggested by @iusergii?

**Comment by minusv** [comment]
It's not working for me as well. Have anyone of you found any solution for this?

**Comment by minusv** [comment]
I tried the solution suggested by @iusergii but it didn't work for me. Does anyone else have a working solution for this? Meanwhile, @iusergii Can you share the full YAML config of your solution? Could be something else that we might be missing.

**Comment by kishorj** [comment]
@minusv, @wwteo, could you share the full manifest of the service? Did you ensure the NLB got provisioned by this controller? If the LB name starts with `k8s-`, then it is provisioned by this controller. Also, check if the ACM certificates are still valid and did not expire.

**Comment by minusv** [comment]
@kishorj Thanks for pointing this out. The NLB created didn't have `k8s-` in the prefix. I checked this document [here](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/configurations/#limiting-ingress-class) and found that ALB-controller will only spawn an LB of type ALB when `--ingress-class=alb` is passed as argument. This was the case in my setup.

Any idea on how can I allow ALB-controller to spawn both nlb and alb in the cluster?

**Comment by kishorj** [comment]
IngressClass is for ALB. For NLB, you will have to provision a service resource of type LoadBalancer, and the following annotations:
```
service.beta.kubernetes.io/aws-load-balancer-type: external
service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
```
or 
```
service.beta.kubernetes.io/aws-load-balancer-type: external
service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
```

You could also set the service `spec.loadBalancerClass` to `service.k8s.aws/nlb` on k8s 1.22 or later in-lieu of the `aws-load-balancer-type` type annotation.

**Comment by kishorj** [comment]
@wwteo, I'm closing the issue since it is possible to attach multiple SSL certificates to the NLB  provisioned by this controller. if you still face issues, feel free to reach out.

**Comment by FalconerTC** [comment]
I'm also running into this issue, with EKS 1.21 and controller 2.4.4. If @iusergii got it to work, I assume it's fixed in EKS 1.22+

**Comment by vivekcode101** [comment]
I am still having the same issue of attaching multiple certs on NLB via annotations
this doesn't work only the first one is getting picked
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:<>,arn:aws:acm:<>"

**Comment by andreferlima** [comment]
It looks like wrong documentation or interpretation. 
Different versions of doc with different explanations.

same issue

In the k8s doc:
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/service/annotations/

> Specifies the ARN of one or more certificates managed by the [AWS Certificate Manager](https://aws.amazon.com/certificate-manager).

But in AWS:
https://docs.aws.amazon.com/pt_br/eks/latest/userguide/auto-configure-nlb.html

> ARN of the SSL certificate from AWS Certificate Manager for HTTPS/TLS.

:(
